package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"time"

	"github.com/Yata-Dash/Yata-Dash/internal/fsperm"
	"github.com/Yata-Dash/Yata-Dash/internal/models"
)

// BackupInfo describes one stored config backup.
type BackupInfo struct {
	Name    string `json:"name"`
	Size    int64  `json:"size"`
	ModTime int64  `json:"mod_time"` // unix seconds
}

// Path returns the config file path.
func (m *Manager) Path() string { return m.path }

// BackupDir returns the directory where config backups are written.
func (m *Manager) BackupDir() string { return m.backupDir }

// Backup writes a timestamped copy of the current config into the backup dir
// and returns the new file's path. Callers may follow it with PruneBackups.
func (m *Manager) Backup() (string, error) {
	m.mu.RLock()
	data, err := json.MarshalIndent(m.cfg, "", "  ")
	m.mu.RUnlock()
	if err != nil {
		return "", err
	}
	// A backup is a verbatim copy of config.json — every tracker API key and
	// session cookie in it. config.json itself is already private (saveLocked
	// writes through os.CreateTemp, which is 0600), so anything looser here
	// just routes around that.
	if err := fsperm.Dir(m.backupDir); err != nil {
		return "", err
	}
	name := fmt.Sprintf("config-backup-%s.json", time.Now().Format("20060102-150405"))
	dst := filepath.Join(m.backupDir, name)
	if err := os.WriteFile(dst, data, fsperm.FileMode); err != nil {
		return "", err
	}
	// WriteFile's mode is masked by umask and ignored entirely if the file
	// already exists, so set it explicitly rather than trusting the create.
	_ = fsperm.File(dst)
	return dst, nil
}

// HardenBackups tightens the backup directory and every backup already in it.
// Called at startup: backups written by an earlier version are world-readable,
// and those are the ones with a history of credentials in them.
func (m *Manager) HardenBackups() error {
	if _, err := os.Stat(m.backupDir); os.IsNotExist(err) {
		return nil // nothing written yet
	}
	if err := fsperm.Dir(m.backupDir); err != nil {
		return err
	}
	list, err := m.ListBackups()
	if err != nil {
		return err
	}
	paths := make([]string, 0, len(list))
	for _, b := range list {
		paths = append(paths, filepath.Join(m.backupDir, b.Name))
	}
	return fsperm.Files(paths...)
}

// ListBackups returns the stored backups, newest first.
func (m *Manager) ListBackups() ([]BackupInfo, error) {
	entries, err := os.ReadDir(m.backupDir)
	if os.IsNotExist(err) {
		return []BackupInfo{}, nil
	}
	if err != nil {
		return nil, err
	}
	out := []BackupInfo{}
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".json" {
			continue
		}
		info, err := e.Info()
		if err != nil {
			continue
		}
		out = append(out, BackupInfo{Name: e.Name(), Size: info.Size(), ModTime: info.ModTime().Unix()})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ModTime > out[j].ModTime })
	return out, nil
}

// PruneBackups keeps the newest `keep` backups and deletes the rest.
func (m *Manager) PruneBackups(keep int) error {
	if keep < 1 {
		keep = 1
	}
	list, err := m.ListBackups()
	if err != nil {
		return err
	}
	for i := keep; i < len(list); i++ {
		_ = os.Remove(filepath.Join(m.backupDir, list[i].Name))
	}
	return nil
}

// LastBackupTime returns the modification time of the newest backup.
func (m *Manager) LastBackupTime() (time.Time, bool) {
	list, err := m.ListBackups()
	if err != nil || len(list) == 0 {
		return time.Time{}, false
	}
	return time.Unix(list[0].ModTime, 0), true
}

// trackerIDRe is the tracker-ID grammar. It matches the character class the
// frontend's jsId() will accept, deliberately: an ID that reaches the browser
// and fails that check makes the tracker's buttons inert, which is a confusing
// way to find out the config was bad.
//
// IDs are generated by the server (16 hex characters), so nothing legitimate
// is near this boundary. Import is the one route by which an arbitrary one can
// arrive, and the value lands in HTML id attributes and inline event handlers.
var trackerIDRe = regexp.MustCompile(`^[A-Za-z0-9_-]{1,64}$`)

// validateTrackerIDs rejects a config whose tracker IDs are unusable.
//
// Rejected rather than sanitised. An ID is the key every stat layer, history
// row and scrape-log entry is filed under, so rewriting one on the way in
// would silently orphan all of that tracker's stored data — the import would
// appear to succeed and the history would be gone. Refusing tells the user
// something is wrong while their data is still intact.
func validateTrackerIDs(trackers []models.Tracker) error {
	seen := make(map[string]bool, len(trackers))
	for i, t := range trackers {
		switch {
		case t.ID == "":
			return fmt.Errorf("tracker %d (%q) has no id", i+1, t.Name)
		case !trackerIDRe.MatchString(t.ID):
			return fmt.Errorf("tracker %d (%q) has an invalid id %q: "+
				"ids may contain only letters, digits, hyphen and underscore", i+1, t.Name, t.ID)
		case seen[t.ID]:
			return fmt.Errorf("tracker %d (%q) repeats the id %q; ids must be unique", i+1, t.Name, t.ID)
		}
		seen[t.ID] = true
	}
	return nil
}

// Import replaces the entire config with the supplied JSON. The current config
// is backed up first (safety net for this destructive action). The raw JSON
// must contain a "settings" object to be accepted as a Yata config.
func (m *Manager) Import(data []byte) error {
	// Sanity check: reject arbitrary JSON that isn't a Yata config.
	var probe map[string]json.RawMessage
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("invalid JSON: %w", err)
	}
	if _, ok := probe["settings"]; !ok {
		return fmt.Errorf("not a Yata config (missing \"settings\")")
	}
	var incoming models.Config
	if err := json.Unmarshal(data, &incoming); err != nil {
		return fmt.Errorf("invalid config: %w", err)
	}
	if err := validateTrackerIDs(incoming.Trackers); err != nil {
		return err
	}
	// An import replaces the whole settings object, so it has to answer the
	// same question the settings handler does — otherwise a crafted config is
	// a way to set allowed_hosts to "*" and switch the host guard off.
	cleanedHosts, err := CleanAllowedHosts(incoming.Settings.AllowedHosts)
	if err != nil {
		return fmt.Errorf("allowed_hosts: %w", err)
	}
	incoming.Settings.AllowedHosts = cleanedHosts

	// Always back up the current config before overwriting it.
	if _, err := m.Backup(); err != nil {
		return fmt.Errorf("backup before import failed: %w", err)
	}

	m.mu.Lock()
	defer m.mu.Unlock()
	m.cfg = incoming
	// Reuse the same defaulting the loader applies.
	if m.cfg.Server.Host == "" {
		m.cfg.Server.Host = "0.0.0.0"
	}
	if m.cfg.Server.Port == 0 {
		m.cfg.Server.Port = 8420
	}
	if m.cfg.Settings.ScrapeIntervalMinutes < 60 {
		m.cfg.Settings.ScrapeIntervalMinutes = 60
	}
	if m.cfg.Settings.QUIEnabledInstances == nil {
		m.cfg.Settings.QUIEnabledInstances = []int{}
	}
	if m.cfg.Trackers == nil {
		m.cfg.Trackers = []models.Tracker{}
	}
	normalizeBackup(&m.cfg.Settings)
	return m.saveLocked()
}
