package config

import (
	"encoding/json"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Yata-Dash/Yata-Dash/internal/models"
)

// Tracker IDs are generated by the server, so config import is the only route
// by which an arbitrary one can arrive. The value lands in HTML id attributes
// and inline event handlers in the dashboard, and the dashboard can read
// /api/config/export — every API key and session cookie the user has.

func importWith(t *testing.T, trackers []models.Tracker) error {
	t.Helper()
	m, err := Open(filepath.Join(t.TempDir(), "config.json"))
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	payload := map[string]any{
		"settings": map[string]any{},
		"trackers": trackers,
	}
	data, err := json.Marshal(payload)
	if err != nil {
		t.Fatal(err)
	}
	return m.Import(data)
}

func TestImportRejectsHostileTrackerIDs(t *testing.T) {
	hostile := []struct {
		name string
		id   string
	}{
		{"breaks out of a quoted attribute", `x" onmouseover="alert(1)`},
		{"breaks out of an inline handler", `x'); alert(1); //`},
		{"html entity that decodes inside a handler", `x&#39;); alert(1); //`},
		{"closes the tag", `x><script>alert(1)</script>`},
		{"empty", ``},
		{"whitespace", `has space`},
		{"over the length bound", strings.Repeat("a", 65)},
	}
	for _, c := range hostile {
		t.Run(c.name, func(t *testing.T) {
			err := importWith(t, []models.Tracker{{ID: c.id, Name: "Example", URL: "https://example.invalid"}})
			if err == nil {
				t.Fatalf("import accepted a tracker id of %q", c.id)
			}
		})
	}
}

func TestImportRejectsDuplicateIDs(t *testing.T) {
	err := importWith(t, []models.Tracker{
		{ID: "abc123", Name: "One", URL: "https://one.invalid"},
		{ID: "abc123", Name: "Two", URL: "https://two.invalid"},
	})
	if err == nil {
		t.Fatal("import accepted two trackers sharing an id")
	}
	if !strings.Contains(err.Error(), "unique") {
		t.Errorf("error should explain the problem, got %q", err)
	}
}

// A rejection has to name the offending entry — the user's next move is to
// open the file and fix it.
func TestImportErrorIdentifiesTheTracker(t *testing.T) {
	err := importWith(t, []models.Tracker{
		{ID: "goodone", Name: "Fine", URL: "https://fine.invalid"},
		{ID: "bad id", Name: "Broken", URL: "https://broken.invalid"},
	})
	if err == nil {
		t.Fatal("expected rejection")
	}
	if !strings.Contains(err.Error(), "Broken") {
		t.Errorf("error %q does not name the offending tracker", err)
	}
}

func TestImportAcceptsGeneratedIDs(t *testing.T) {
	// The shape newID() produces: 16 hex characters.
	if err := importWith(t, []models.Tracker{
		{ID: "3f9a1c7e5b2d8046", Name: "Example", URL: "https://example.invalid"},
		{ID: "legacy_id-2", Name: "Older", URL: "https://older.invalid"},
	}); err != nil {
		t.Fatalf("import rejected legitimate ids: %v", err)
	}
}

// A config with no trackers at all is a normal thing to import.
func TestImportAcceptsNoTrackers(t *testing.T) {
	if err := importWith(t, nil); err != nil {
		t.Fatalf("import rejected an empty tracker list: %v", err)
	}
}
